#### D2: Table C1 ###############
# Function: Build Table C1 — simulated mean WTP by attribute, level, class, and insect
# Author: Dr Peter King (p.king1@leeds.ac.uk)
# Last Edited: 20/06/2026
# Changes:
## - New script (table-building code extracted from 08_Druid_Model_SimulatedMeanWTP.R)
## - Reads pre-computed Wide CSV (output of 08, generated from V3 model)
## - Outputs formatted Table C1 matching SI structure (mean + 95% CI per cell)

# **********************************************************************************
#### Section 0: Replication Information ####
# **********************************************************************************

# here() = "C:/Users/earpkin/OneDrive - University of Leeds/DRUID/D2/Analysis/D2Backup"
# ─ Session info ─────────────────────────────────────
# setting  value
# version  R version 4.5.0 (2025-04-11 ucrt)
# os       Windows 11 x64 (build 22631)
# system   x86_64, mingw32
# ui       RStudio
# language (EN)
# collate  English_United Kingdom.utf8
# ctype    English_United Kingdom.utf8
# tz       Europe/London
# date     2025-05-20
# rstudio  2023.06.2+561 Mountain Hydrangea (desktop)
# pandoc   NA
#
# ─ Packages ─────────────────────────────────────────
# package      * version    date (UTC) lib source
# data.table   * 1.17.2     2025-05-12 [1] CRAN (R 4.5.0)
# here         * 1.0.1      2020-12-13 [1] CRAN (R 4.5.0)
# magrittr     * 2.0.3      2022-03-30 [1] CRAN (R 4.5.0)
#
# [1] C:/Users/earpkin/AppData/Local/Programs/R/R-4.5.0/library
# * ── Packages attached to the search path.

library(data.table)
library(magrittr)
library(here)


# **********************************************************************************
#### Section 1: Import data ####
# **********************************************************************************


## Wide CSV: 450,000 rows × 9 cols (Class, insect, wellbeing, 6 attribute-level cols).
## Generated by 08_Druid_Model_SimulatedMeanWTP.R using the V3 model.
## Column name mapping: Medium = Small increase, High = Large increase.
all_results <- fread(here("CEOutput/Main/LCM",
                          "D2_Truncated_LC_3C_MXL_NoDR_V3_SimulatedMeans_Wide.csv"))


## Posterior class membership probabilities → expected class sizes.
## PiValues is an N_respondents × 3 matrix of posterior class probabilities.
PiValues    <- readRDS(here("CEOutput/Main/LCM",
                            "D2_Truncated_LC_3C_MXL_NoDR_V3_model_PiValues.rds"))
## PiValues is a named list (Class1, Class2, Class3) of per-respondent probabilities.
class_props <- sapply(PiValues, mean)
class_props <- class_props / sum(class_props)


# **********************************************************************************
#### Section 2: Filter and reshape ####
# **********************************************************************************

## Table C1 reports WTP at mean wellbeing (wellbeing = 0), so the wellbeing
## interaction term drops out, giving the baseline class-specific WTP.
base <- all_results[wellbeing == 0]

## Add draw index within each class × insect group so we can pair draws
## across classes when computing the weighted "All classes" CI.
base[, draw_id := seq_len(.N), by = .(Class, insect)]

## Reshape attribute-level columns to long format.
attr_cols <- c("Encounter_High", "Encounter_Medium",
               "Existence_High", "Existence_Medium",
               "Bequest_High",   "Bequest_Medium")

long <- melt(base,
             id.vars      = c("Class", "insect", "draw_id"),
             measure.vars = attr_cols,
             variable.name = "attr_col",
             value.name    = "wtp")
setDT(long)

long[, Attribute := sub("_.*", "", attr_col)]
long[, Level     := fifelse(grepl("High", attr_col), "Large", "Small")]
long[, attr_col  := NULL]


# **********************************************************************************
#### Section 3: Compute per-class summaries ####
# **********************************************************************************

class_summary <- long[, .(
  mean_wtp = mean(wtp),
  lo       = quantile(wtp, 0.025),
  hi       = quantile(wtp, 0.975)
), by = .(Attribute, Level, Class, insect)]

class_label_map <- c("1" = "1: Pro-insect",
                     "2" = "2: Insect-averse",
                     "3" = "3: Ambivalent")
class_summary[, Class_label := class_label_map[as.character(Class)]]
class_summary[, Class_order := Class]


# **********************************************************************************
#### Section 4: Compute weighted "All classes" row ####
# **********************************************************************************

## Pair draws across classes by draw_id (same index within each insect × wellbeing
## group). The weighted combination per draw gives a proper Monte Carlo distribution
## for the aggregate WTP.
wide_for_weight <- dcast(long,
                         Attribute + Level + insect + draw_id ~ Class,
                         value.var = "wtp")
setDT(wide_for_weight)
setnames(wide_for_weight, c("1", "2", "3"), c("c1", "c2", "c3"))

wide_for_weight[, weighted_wtp := class_props[1] * c1 +
                                  class_props[2] * c2 +
                                  class_props[3] * c3]

all_classes <- wide_for_weight[, .(
  mean_wtp    = mean(weighted_wtp),
  lo          = quantile(weighted_wtp, 0.025),
  hi          = quantile(weighted_wtp, 0.975),
  Class       = 4L,
  Class_label = "All classes",
  Class_order = 4L
), by = .(Attribute, Level, insect)]


# **********************************************************************************
#### Section 5: Combine, format, and pivot ####
# **********************************************************************************

combined <- rbind(
  class_summary[, .(Attribute, Level, insect, Class_order, Class_label, mean_wtp, lo, hi)],
  all_classes[,   .(Attribute, Level, insect, Class_order, Class_label, mean_wtp, lo, hi)]
)

## Format each cell as "mean (lower - upper)" with 2 decimal places.
combined[, cell := sprintf("%.2f (%.2f - %.2f)", mean_wtp, lo, hi)]

## Pivot insect to columns (Bee, Beetle, Wasp) to match SI table layout.
TableC1 <- dcast(combined,
                 Attribute + Level + Class_order + Class_label ~ insect,
                 value.var = "cell")
setDT(TableC1)

## Set display order: Encounter → Existence → Bequest; Large → Small; Class 1–3 → All.
TableC1[, attr_order  := match(Attribute, c("Encounter", "Existence", "Bequest"))]
TableC1[, level_order := match(Level,     c("Large", "Small"))]
setorder(TableC1, attr_order, level_order, Class_order)
TableC1[, c("attr_order", "level_order", "Class_order") := NULL]
setnames(TableC1, "Class_label", "Class")
setcolorder(TableC1, c("Attribute", "Level", "Class", "Bee", "Beetle", "Wasp"))


# **********************************************************************************
#### Section 6: Export ####
# **********************************************************************************


TableC1 %>% 
  fwrite(here("OtherOutput/Tables", "TableC1_SimulatedMeanWTP.csv"),
       sep   = ",",
       quote = TRUE)


# End Of Script **************************************************************
